"""empty message

Revision ID: 71fba79fc470
Revises: cffb0eac8a28
Create Date: 2022-03-16 16:40:10.447123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71fba79fc470'
down_revision = 'cffb0eac8a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'url')
    # ### end Alembic commands ###
