"""empty message

Revision ID: 8ddb748eaa3c
Revises: e4614374f566
Create Date: 2022-03-23 15:58:50.531741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ddb748eaa3c'
down_revision = 'e4614374f566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home', sa.Column('vi', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'home', ['vi'])
    op.drop_column('home', 'vin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home', sa.Column('vin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'home', type_='unique')
    op.drop_column('home', 'vi')
    # ### end Alembic commands ###
